hotel/urls.py
from django.urls import path
from .views import dashboard_hotel
app_name = 'hotel'

urlpatterns = [
    path('dashboard/', dashboard_hotel, name= 'dashboard-hotel'),
]

reservasi/urls.py
from django.urls import path
from .views import *
app_name = 'reservasi'

urlpatterns = [
    path('', show_reservasi_kamar, name= 'show-reservasi'),
    path('complaint/<str:id>', complaint, name= 'complaint'),
    path('complaint/<str:id>/save', save_complaint, name= 'complaint-save'),
    path('buat', buat_reservasi, name= 'buat-reservasi'),
    path('detail/<str:id>', detail_reservasi, name= 'detail-reservasi'),
    path('complaint/<str:id>', complaint, name= 'complaint'),
    path('complaint/<str:id>/save', save_complaint, name= 'complaint-save'),
    path('cancel/<str:id>', cancel_reservasi, name= 'cancel-reservasi'),
    path('dashboard/', dashboard_pengguna, name= 'dashboard-pengguna'),
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotel.urls')),
    path('hotels/', include('hotels_and_reviews.urls')),
    path('reservasi/', include('reservasi.urls')),
    path('', include('authentication.urls')),
    path('reservasi-hotel/', include('reservasi_hotel.urls')),
    path('fasilitas/', include('fasilitas.urls')),

    path('kamar-hotel/', include('kamar_hotel.urls')),
]

reservasi/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from connect_postgres import execute_sql_query
import random
from datetime import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse
from connect_postgres import execute_sql_query, execute_sql_query_no_fetch
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def show_reservasi_kamar(request):
    user_data = request.session.get('user_data') 
    
    if not user_data:
        return redirect('/login/')
    custemail = request.session['user_data']['email']
    query = f""" 
                SELECT rr.rsv_id, rr.rNum, rr.rhotelname, rr.rhotelbranch, rr.Datetime, rr.isActive, rs.status
                FROM reservation r
                JOIN reservation_room rr ON r.rID = rr.rsv_id
                JOIN reservation_status_history rsh ON r.rID = rsh.rid
                JOIN reservation_status rs ON rs.id = rsh.rsid
                WHERE r.cust_email = '{custemail}'
                """
    res = execute_sql_query(query=query)

    data = []
    for row in res:
        data.append({
            'rsv_id': row[0],
            'rnum': row[1],
            'rhotelname': row[2],
            'rhotelbranch': row[3],
            'Datetime': row[4],
            'isActive': row[5],
            'status': row[6],
        })
    print(data)
    context = {
        "data": data,
    }
    return render(request, "daftar-reservasi-kamar.html", context)

@csrf_exempt
def complaint(request, id):
    user_data = request.session['user_data']
    custemail = user_data['email']
    if not user_data:
        return redirect('/login/')

    query = f"""
        SELECT rr.rsv_id, rr.rNum, rr.rhotelname, rr.rhotelbranch
        FROM reservation r
        JOIN reservation_room rr ON r.rID = rr.rsv_id
        WHERE r.cust_email = '{custemail}' AND r.rID = '{id}'
    """

    res = execute_sql_query(query=query)

    if len(res) > 0:
        row = res[0]
        data = {
            'rsv_id': row[0],
            'rnum': row[1],
            'rhotelname': row[2],
            'rhotelbranch': row[3],
        }

    context = {
        'id': id,
        'data': data,
        'user_data': {
            'email': user_data['email'],
            'name': user_data['fname'] + " " + user_data['lname']
        }
    }
    print(context)
    return render(request, "complaint-reservasi.html", context)

@csrf_exempt
def save_complaint(request, id):
    def increment_string(id):

        letter_part = ''.join(filter(str.isalpha, id))
        number_part = ''.join(filter(str.isdigit, id))

        incremented_number = str(int(number_part) + 1)

        result_string = letter_part + incremented_number

        return result_string
    
    if request.method == 'POST':

        complaint_message = request.POST.get('complaintMessage')
        email = request.POST.get('email')

        query_latest_id = f"""
        SELECT * FROM complaints ORDER BY id DESC LIMIT 1
        """

        res = execute_sql_query(query=query_latest_id)

        latest_complaint_id = increment_string(res[0][0])

        query = f"""
            INSERT INTO complaints (id, cust_email, rv_id, complaint)
            VALUES ('{latest_complaint_id}', '{email}', '{id}', '{complaint_message}')
            RETURNING id;
        """

        execute_sql_query(query=query)

        return redirect('reservasi:show-reservasi')

    return HttpResponse("Invalid request method")

@csrf_exempt
def dashboard_pengguna(request):
    user_data = request.session['user_data']
    if not user_data:
        return redirect('/login/')
    query = f"""
    SELECT CUSTOMER.nik, RESERVATION_ACTOR.phonenum FROM CUSTOMER LEFT JOIN  RESERVATION_ACTOR ON
    CUSTOMER.email = RESERVATION_ACTOR.email
    WHERE CUSTOMER.email = '{user_data['email']}' LIMIT 1;
    """
    res = execute_sql_query(query=query)
    res = res[0]
    nik = res[0]
    phonenum = res[1]    
    query_recent_comments = f"""
    SELECT DISTINCT review, hotel_name, hotel_branch, rating FROM REVIEWS WHERE cust_email = '{user_data['email']}';
"""
    res_comment = execute_sql_query(query_recent_comments)
    comments = []
    complaints = []
    query_complaints = f"""
    SELECT DISTINCT COMPLAINTS.complaint, RESERVATION_ROOM.rhotelname, RESERVATION_ROOM.rhotelbranch
    , RESERVATION_ROOM.rnum
    FROM COMPLAINTS INNER JOIN RESERVATION_ROOM ON COMPLAINTS.rv_id = RESERVATION_ROOM.rsv_id 
    WHERE COMPLAINTS.cust_email = '{user_data['email']}';
"""
    res_complaints = execute_sql_query(query_complaints)
    for complaint in res_complaints:
        complaints.append(
            {
                'text': complaint[0],
                'hotel_name': complaint[1],
                'hotel_branch': complaint[2],
                'room_number': complaint[3].split('.')[0]
            }
        )
    for comment in res_comment:
        comments.append(
            {
                'text': comment[0],
                'hotel_name': comment[1],
                'hotel_branch': comment[2],
                'rating': comment[3]
            }
        )
    return render(request, 'dashboard-pengguna.html', 
                  {'user_data': user_data, 'nik':nik, 'phone':phonenum, 
                                                      'complaints':complaints ,'comments':comments})

@csrf_exempt
def buat_reservasi(request):
    def generate_random_string(length):
        random_string = ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', k=length))
        return random_string
    
    def generate_payment_id():
        part1 = ''.join(random.choices('0123456789', k=3))
        part2 = ''.join(random.choices('0123456789', k=2))
        part3 = ''.join(random.choices('0123456789', k=4))
        random_string = f"{part1}-{part2}-{part3}"
        return random_string
    
    if request.method == 'POST':

        user_data = request.session['user_data']
        email = user_data['email']

        hotel_name = request.POST.get('hotel_name')
        hotel_branch = request.POST.get('hotel_branch')
        number = request.POST.get('number')

        checkin = request.POST.get('start-date')
        checkout = request.POST.get('end-date')
        payment_option = request.POST.get('payment-option')
        payment = request.POST.get('payment')
        payment_id = generate_payment_id()

        create_payment = execute_sql_query_no_fetch(f"""
        INSERT INTO payment (payment_id, status) VALUES ('{payment_id}', 'pending')
        """)

        payment_query = ""
        if payment_option == 'kredit':
            payment_query += f"""
            INSERT INTO kredit (no_kartu, payment_id) VALUES ('{payment}', '{payment_id}')
            """
        elif payment_option == 'debit':
            payment_query += f"""
            INSERT INTO debit (no_rekening, payment_id) VALUES ('{payment}', '{payment_id}')
            """
        elif payment_option == 'ewallet':
            payment_query += f"""
            INSERT INTO ewallet (phone_num, payment_id) VALUES ('{payment}', '{payment_id}')
            """

        create_payment_method = execute_sql_query_no_fetch(payment_query)

        rid = generate_random_string(20)

        hotel = execute_sql_query(f"""
        SELECT * FROM room WHERE 
        hotel_name = '{hotel_name}' AND 
        hotel_branch = '{hotel_branch}' AND 
        number = '{number}.0'
        """)

        hotel = hotel[0]

        reservation_query = execute_sql_query_no_fetch(f"""
        INSERT INTO reservation (rid, total_price, checkin, checkout, payment, cust_email)
        VALUES('{rid}', '{hotel[3]}', '{checkin}', '{checkout}', '{payment_id}', '{email}')
        """)
        formatted_datetime = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        reservation_status_query = execute_sql_query_no_fetch(f"""
        INSERT INTO reservation_status_history (rid, rsid, datetime)
        VALUES('{rid}', 'A7B1D9E4F2C5G3H0', '{formatted_datetime}')
        """)

        date = datetime.today().strftime('%Y-%m-%d')

        reservation_room_query = execute_sql_query_no_fetch(f"""
        INSERT INTO reservation_room (rsv_id, rnum, rhotelname, rhotelbranch, datetime, isactive)
        VALUES('{rid}', '{number}.0', '{hotel_name}', '{hotel_branch}', '{date}', 'false')
        """)

        print(reservation_room_query)

        return redirect('reservasi:show-reservasi')
    else:
        return render(request, 'buat-reservasi.html')
    
@csrf_exempt
def detail_reservasi(request, id):
    room_query = execute_sql_query(f"""
    SELECT * FROM reservation_room
    WHERE rsv_id = '{id}'
    """)

    hotel = room_query[0]

    hotel_data = {
        'id': hotel[0],
        'room_number': hotel[1],
        'hotel_name': hotel[2],
        'hotel_branch': hotel[3],
        'date': hotel[4],
        'status': hotel[5],
    }

    shuttle_query = execute_sql_query(f"""
    SELECT * FROM reservation_shuttleservice
    WHERE rsv_id = '{id}'
    """)

    shuttle_data = {}
    if(shuttle_query):
        shuttle = shuttle_query[0]

        shuttle_data = {
            'id': shuttle[0],
            'vehicle_num': shuttle[1],
            'driver_phonenum': shuttle[2],
            'date': shuttle[3],
            'status': shuttle[4],
        }

    context = {
        'room': hotel_data,
        'shuttle': shuttle_data,
        'rsv_id': id
    }

    print(context)

    return render(request, 'detail-reservasi.html', context)
@csrf_exempt
def cancel_reservasi(request, id):
    update_status = execute_sql_query_no_fetch(f"""
    UPDATE  reservation_status_history 
     SET rsid = 'gVmGZxNrVbOgGTYyhTnb' WHERE rid = '{id}'
    """)

    return redirect('reservasi:show-reservasi')

reservasi/templates/buat-reservasi.html
{% extends 'base-tw.html' %} 
{% load static %} 
{% block meta %}
  <title>Reservasi Kamar</title>
{% endblock meta %} 
{% block content %} 
  {% include 'nav.html' with is_hotel=is_hotel %}
  <div class="max-w-7xl my-20 min-h-screen mx-auto flex flex-col items-center w-screen px-4">
    <h1 class="text-3xl font-bold my-8">Reservasi Form</h1>

    <form action="{% url 'reservasi:buat-reservasi' %}" method="post" class="max-w-md w-full">
      {% csrf_token %}

      <input type="hidden" name="hotel_name" value="{{ request.GET.hotel_name }}">
      <input type="hidden" name="hotel_branch" value="{{ request.GET.hotel_branch }}">
      <input type="hidden" name="number" value="{{ request.GET.number }}">

      <div class="mb-4">
        <label for="start-date" class="block text-sm font-medium text-gray-600">Start Date</label>
        <input
          type="date"
          id="start-date"
          name="start-date"
          class="mt-1 p-2 w-full border rounded-md"
          value="{% now 'Y-m-d' %}"
          min="{% now 'Y-m-d' %}"
        />
      </div>

      <div class="mb-4">
        <label for="end-date" class="block text-sm font-medium text-gray-600">End Date</label>
        <input
          type="date"
          id="end-date"
          name="end-date"
          class="mt-1 p-2 w-full border rounded-md"
          min="{% now 'Y-m-d' %}"
        />
      </div>

      <div class="mb-7">
        <label for="payment-option" class="block text-sm font-medium text-gray-600">Opsi Pembayaran</label>
        <select
          id="payment-option"
          name="payment-option"
          class="mt-1 p-2 w-full border rounded-md"
          onchange="updatePaymentLabel(this.value)"
        >
          <option value="" selected disabled>Select payment method</option>
          <option value="kredit">Kartu Kredit</option>
          <option value="ewallet">E-Wallet</option>
          <option value="debit">Debit</option>
        </select>
        <label for="payment" class="block text-sm font-medium text-gray-600 mt-4" id="payment-label">Payment</label>
        <input
          type="text"
          id="payment"
          name="payment"
          class="mt-1 p-2 w-full border rounded-md"
          disabled
        />
      </div>

      <button
        type="submit"
        class="bg-blue-700 text-white py-2 px-4 rounded-md hover:bg-blue-800 focus:outline-none focus:ring focus:border-blue-300"
      >
        Submit
      </button>
      <button
        type="button"
        onclick="goBack()"
        class="bg-red-700 text-white py-2 px-4 rounded-md hover:bg-red-800 focus:outline-none focus:ring focus:border-red-300"
      >
        Back
      </button>
    </form>
  </div>

  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css" />
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>

  {% if not is_authorized %}
    <script>
      function goBack() {
        window.history.back();
      }

      document.getElementById("back-btn").addEventListener("click", () => {
        goBack();
      });

      function updatePaymentLabel(selectedPaymentOption) {
        const paymentLabel = document.getElementById("payment-label");
        const paymentInput = document.getElementById("payment");

        paymentInput.disabled = false;

        // Update the label based on the selected payment option
        switch (selectedPaymentOption) {
          case "kredit":
            paymentLabel.textContent = "Credit Card Number";
            break;
          case "ewallet":
            paymentLabel.textContent = "Phone Number";
            break;
          case "debit":
            paymentLabel.textContent = "Debit Card Number";
            break;
          default:
            paymentLabel.textContent = "Payment";
        }
        paymentInput.value = "";
      }
    </script>
  {% endif %}
{% endblock content %}

reservasi/templates/complaint-reservasi.html
{% extends 'base-tw.html' %} {% load static %} {% block meta %}
<title>Reservasi Kamar</title>
{% endblock meta %} {% block content %} {% include 'nav.html' with is_hotel=is_hotel %}
<div
  class="max-w-7xl my-20 min-h-screen mx-auto flex flex-col items-center w-screen px-4"
>
  <h1 class="text-3xl font-bold my-8">Complaint Form</h1>

  <form action="{% url 'reservasi:complaint-save' id %}" method="post" class="max-w-md w-full">
    {% csrf_token %}
    <!-- Email Input -->
    <div class="mb-4">
      <label for="email" class="block text-sm font-medium text-gray-600"
        >Email</label
      >
      <input
        type="email"
        id="email"
        name="email"
        value="{{ user_data.email }}"
        class="mt-1 p-2 w-full border rounded-md"
        readonly
      />
    </div>

    <!-- Name Input -->
    <div class="mb-4">
      <label for="name" class="block text-sm font-medium text-gray-600"
        >Name</label
      >
      <input
        type="text"
        id="name"
        name="name"
        value="{{ user_data.name }}"
        class="mt-1 p-2 w-full border rounded-md"
        readonly
      />
    </div>

    <!-- Hotel Name Input -->
    <div class="mb-4">
      <label for="hotelName" class="block text-sm font-medium text-gray-600"
        >Hotel Name</label
      >
      <input
        type="text"
        id="hotelName"
        name="hotelName"
        value="{{ data.rhotelname }}"
        class="mt-1 p-2 w-full border rounded-md"
        readonly
      />
    </div>

    <!-- Branch Name Input -->
    <div class="mb-4">
      <label for="branchName" class="block text-sm font-medium text-gray-600"
        >Branch Name</label
      >
      <input
        type="text"
        id="branchName"
        name="branchName"
        value="{{ data.rhotelbranch }}"
        class="mt-1 p-2 w-full border rounded-md"
        readonly
      />
    </div>

    <!-- Complaint Message Input -->
    <div class="mb-4">
      <label
        for="complaintMessage"
        class="block text-sm font-medium text-gray-600"
        >Complaint Message</label
      >
      <textarea
        id="complaintMessage"
        name="complaintMessage"
        rows="4"
        class="mt-1 p-2 w-full border rounded-md"
        required
      ></textarea>
    </div>

    <!-- Submit Button -->
    <button
      type="submit"
      class="bg-blue-700 text-white py-2 px-4 rounded-md hover:bg-blue-800 focus:outline-none focus:ring focus:border-blue-300"
    >
      Submit
    </button>
  </form>
</div>
<link
  rel="stylesheet"
  type="text/css"
  href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css"
/>
<script
  type="text/javascript"
  src="https://cdn.jsdelivr.net/npm/toastify-js"
></script>

{% if not is_authorized %}
<script>
  function goBack() {
    window.history.back();
  }
  document.getElementById("back-btn").addEventListener("click", () => {
    goBack();
  });
</script>
{% endif %} {% endblock content %}

reservasi/templates/daftar-reservasi-kamar.html
{% extends 'base-tw.html' %}
{% load static %}
{% block meta %}
    <title>Reservasi Kamar</title>
{% endblock meta %}

{% block content %}
{% include 'nav.html' with is_hotel=is_hotel %}
<div class="max-w-7xl mt-16 min-h-screen mx-auto flex flex-col items-center  w-screen px-4 " >   

    {% if data|length > 0 %}
    <div class="w-full my-10">
        <table class="min-w-full table-auto border border-gray-200 rounded-lg overflow-hidden outline outline-slate-200">
            <thead>
                <tr>
                    <th class="border-b bg-blue-500 text-white p-4">ID Reservasi</th>
                    <th class="border-b bg-blue-500 text-white p-4">Nomor Kamar</th>
                    <th class="border-b bg-blue-500 text-white p-4">Nama Hotel</th>
                    <th class="border-b bg-blue-500 text-white p-4">Cabang Hotel</th>
                    <th class="border-b bg-blue-500 text-white p-4">Date</th>
                    <th class="border-b bg-blue-500 text-white p-4">Status Reservasi</th>
                    <th class="border-b bg-blue-500 text-white p-4">Status</th>
                    <th class="border-b bg-blue-500 text-white p-4">Action</th>
                </tr>
            </thead>
            <tbody>
                {% for rsv in data %}
                    <tr class="text-center">
                        <td class="border-b p-4">{{ rsv.rsv_id }}</td>
                        <td class="border-b p-4">{{ rsv.rnum }}</td>
                        <td class="border-b p-4">{{ rsv.rhotelname }}</td>
                        <td class="border-b p-4">{{ rsv.rhotelbranch }}</td>
                        <td class="border-b p-4 whitespace-nowrap">{{ rsv.Datetime }}</td>
                        <td class="border-b p-4">
                            <span class="{% if rsv.isActive %}text-green-500{% else %}text-red-500{% endif %}">
                                {% if rsv.isActive %}Active{% else %}Inactive{% endif %}
                            </span>
                        </td>
                        <td class="border-b p-4">
                           
                            <span class="">
                                {{ rsv.status }}
                            </span>
                
                        </td>
                        <td class="border-b p-4 flex gap-1">
                            <a href="{% url 'reservasi:detail-reservasi' rsv.rsv_id %}">
                                <button class="p-2 bg-blue-500 text-white hover:bg-blue-600 rounded">Detail</button>
                            </a>
                            {% if rsv.status == 'Menunggu Konfirmasi Pihak Hotel' %}
                            <a href="{% url 'reservasi:cancel-reservasi' rsv.rsv_id %}">
                                <button class="p-2 bg-red-500 text-white hover:bg-red-600 rounded">Cancel</button>
                            </a>
                            {% else %}
                                <button class="p-2 bg-red-500 text-white hover:bg-red-600 rounded" onclick="showCancelStatusAlert()">Cancel</button>
                            {% endif %}

                            {% if rsv.isActive %}
                            <a href="{% url 'reservasi:complaint' rsv.rsv_id %}">
                                <button class="p-2 bg-gray-500 text-white hover:bg-gray-600 rounded">Complaint</button>
                            </a>
                            {% else %}
                                <button class="p-2 bg-gray-500 text-white hover:bg-gray-600 rounded" onclick="showInactiveStatusAlert()">Complaint</button>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <!-- Tambahkan lebih banyak kartu sesuai kebutuhan -->
      </div>
    </div>
    {% else %}
    <div id="hotel-cards-container" class=" grow  flex justify-center items-center w-full">
        <h1>
            Tidak ada hotel yang sesuai
        </h1>
    </div>
    {% endif %}    
        
    
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script> 


{% if not is_authorized %}
    <script>
        function showInactiveStatusAlert() {
            alert("Complaint submission is disabled for inactive reservations!");
        }
        function showCancelStatusAlert() {
            alert("Tidak dapat membetalkan reservasi!");
        }
        function goBack() {
            window.history.back();
        }
        document.getElementById('back-btn').addEventListener('click',()=>{
            goBack()
        })
    </script>
{% endif %}
    
    


{% endblock content %}
    
    

reservasi/templates/dashboard-pengguna.html
{% extends 'base-tw.html' %}
{% load static %}
{% block meta %}
    <title>Reservasi Kamar</title>
{% endblock meta %}

{% block content %}
{% include 'nav.html' with is_hotel=user_data.is_hotel %}
<div class="max-w-7xl mt-16 min-h-screen mx-auto flex flex-col items-center  w-screen px-4 " >   

    <div class="container mx-auto mt-8 p-6 bg-gray-100 rounded-lg shadow-md">
        <h1 class="text-3xl font-bold mb-6 text-blue-700">Dashboard Pengguna</h1>
    
        <div class="grid grid-cols-1 gap-8">
            <!-- Profile Information Card -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h2 class="text-xl font-bold mb-4 text-gray-800">Profile Information</h2>
                <div class="mb-4">
                    <span class="block text-sm text-gray-600">First Name:</span>
                    <span class="text-lg text-gray-800 font-semibold">{{ user_data.fname }}</span>
                </div>
                <div class="mb-4">
                    <span class="block text-sm text-gray-600">Last Name:</span>
                    <span class="text-lg text-gray-800 font-semibold">{{ user_data.lname }}</span>
                </div>
                <div class="mb-4">
                    <span class="block text-sm text-gray-600">Phone Number:</span>
                    <span class="text-lg text-gray-800 font-semibold">{% if phone %} {{phone}}  {% else %} Not Set {% endif %}</span>
                </div>
                <div class="mb-4">
                    <span class="block text-sm text-gray-600">Email:</span>
                    <span class="text-lg text-gray-800 font-semibold">{{ user_data.email }}</span>
                </div>
                <div class="mb-4">
                    <span class="block text-sm text-gray-600">NIK:</span>
                    <span class="text-lg text-gray-800 font-semibold">{% if nik %} {{nik}}  {% else %} Not Set {% endif %}</span>
                </div>
            </div>
    
            <!-- Additional Information Card -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h2 class="text-xl font-bold mb-4 text-gray-800">Recent Activity</h2>
                <!-- Add widgets or information about recent activity here -->
                {% for complaint in complaints  %}
                <div class="complaint">
                    <h3 class="font-bold text-lg mb-2">Anda memberikan komplain pada <span class="hotel-name">{{complaint.hotel_name}}</span> <span class="hotel-branch">{{complaint.hotel_branch}}</span>:</h3>
                    <p class="text-gray-700">{{complaint.text}}</p>
                    <p class="rating">Kamar {{complaint.room_number}}</p>
                </div> 
                {% endfor %}
                {% for comment in comments  %}

                <div class="review">
                    <h3 class="font-bold text-lg mb-2">Anda memberikan ulasan pada <span class="hotel-name">{{comment.hotel_name}}</span> <span class="hotel-branch">{{comment.hotel_branch}}</span>:</h3>
                    <p class="text-gray-700">{{comment.text}}</p>
                    <p class="rating">{{comment.rating}} bintang</p>
                </div> 
                {% endfor %}
            </div>
    
            <!-- Notification Card -->
            <div class="bg-white p-6 rounded-lg shadow-md">
                <h2 class="text-xl font-bold mb-4 text-gray-800">Notifications</h2>
                <!-- Add notification widgets or information here -->
            </div>
        </div>
    </div>
    
        
    
</div>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script> 


{% if not is_authorized %}
    <script>
        function showInactiveStatusAlert() {
            alert("Complaint submission is disabled for inactive reservations!");
        }
        function goBack() {
            window.history.back();
        }
        document.getElementById('back-btn').addEventListener('click',()=>{
            goBack()
        })
    </script>
{% endif %}
    
    


{% endblock content %}
    
    