hotel/urls.py
from django.urls import path
from .views import dashboard_hotel
app_name = 'hotel'

urlpatterns = [
    path('dashboard/', dashboard_hotel, name= 'dashboard-hotel'),
]

reservasi/urls.py
from django.urls import path
from .views import *
app_name = 'reservasi'

urlpatterns = [
    path('', show_reservasi_kamar, name= 'show-reservasi'),
    path('complaint/<str:id>', complaint, name= 'complaint'),
    path('complaint/<str:id>/save', save_complaint, name= 'complaint-save'),
    path('buat', buat_reservasi, name= 'buat-reservasi'),
    path('detail/<str:id>', detail_reservasi, name= 'detail-reservasi'),
    path('complaint/<str:id>', complaint, name= 'complaint'),
    path('complaint/<str:id>/save', save_complaint, name= 'complaint-save'),
    path('cancel/<str:id>', cancel_reservasi, name= 'cancel-reservasi'),
    path('dashboard/', dashboard_pengguna, name= 'dashboard-pengguna'),
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotel.urls')),
    path('hotels/', include('hotels_and_reviews.urls')),
    path('reservasi/', include('reservasi.urls')),
    path('', include('authentication.urls')),
    path('reservasi-hotel/', include('reservasi_hotel.urls')),
    path('fasilitas/', include('fasilitas.urls')),

    path('kamar-hotel/', include('kamar_hotel.urls')),
]

templates/base-tw.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        <style>
            ::-webkit-scrollbar {
                width: 8px; /* Lebar scrollbar */
                background-color: #333; /* Warna latar belakang scrollbar */
                border-radius: 10px; /* Bentuk rounded */
              }
              
              /* Style thumb (kursor) scrollbar */
              ::-webkit-scrollbar-thumb {
                background-color: #555; /* Warna thumb (kursor) scrollbar */
                border-radius: 10px; /* Bentuk rounded */
              }
              
              /* Style track (jalur) scrollbar */
              ::-webkit-scrollbar-track {
                background-color: #111; /* Warna track (jalur) scrollbar */
                border-radius: 10px; /* Bentuk rounded */
              }
              
              /* Style corner (sudut) scrollbar (jika diperlukan) */
              ::-webkit-scrollbar-corner {
                background-color: #111; /* Warna sudut scrollbar */
                border-radius: 10px; /* Bentuk rounded */
              }
            
        </style>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" type="text/css" href="/static/css/index.css">
        <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
        
        {% block meta %}
        {% endblock meta %}
    </head>
    <body class=" max-w-[100vw] overflow-x-hidden w-screen min-h-screen">
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">


<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap" rel="stylesheet">


</head>

<body>
  {% block content %}
  {% endblock content %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  {% block script %}{% comment %} include external js{% endcomment %}{% endblock %}
</body>


</html>

<style>
  body {
    font-family: 'Roboto', sans-serif !important;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #6f99c0;
    text-align: left;
    background-color: white;
    --bs-primary-rgb: rgb(119 187 188);
  }


  .border-primary {
    border-color: #6f99c0;
  }

  .navbar-light .bg-light {
    background-color: white;
    --bs-bg-opacity: 0
  }

  .nav-link {
    color: #356369;
  }

  .text-primary {
    color: #6f99c0 !important;
  }

  .btn-primary {
    background-color: #6f99c0;;
    --bs-btn-hover-bg: #93cdcd;
    --bs-btn-hover-border-color: #93cdcd;
    --bs-btn-border-color: #93cdcd !important;
  }

 
  .btn-primary:hover {
    background-color: #93cdcd;
  }

  .btn-outline-primary {
    --bs-btn-color: #356369;
    --bs-btn-border-color: #6f99c0;;
    --bs-btn-hover-color: #fff;
    --bs-btn-hover-bg: #6f99c0;;
    --bs-btn-hover-border-color: #6f99c0;;
  }

  .form-select {
    border: 1px solid #212529;
  }

  .border-primary {
    border-color: #ced4da;
  }
  a {
    --bs-link-color: #fff;
    text-decoration: none;
  }
  a:hover {
    --bs-link-hover-color: #fff;
    text-decoration: none;
  }

  .form-check-input:checked {
    background-color: #506e8a;;
  }

  h1 {
    font-weight: 700;
  }

  h2 {
    font-weight: 700;
    
  }

  h3 {
    color: #f2f6fc;
  }
</style>

templates/nav.html
{% if not is_hotel %}
<nav class="bg-blue-700 py-4 px-4 fixed top-0 left-0 w-[100vw] z-20">
    <div class="container mx-auto flex items-center justify-between">
        <div class="px-4">
            <a href="#" class="text-white font-bold text-2xl">Sistel</a>
        </div>
        <div class="hidden md:block"> <!-- Hanya tampil di layar besar (md dan yang lebih besar) -->
            <ul class="flex space-x-4 items-center">
                <li><a href="{% url 'reservasi:dashboard-pengguna' %}" class="text-white hover:text-gray-300">Dashboard Pengguna</a></li>
                <li><a href="{% url 'reservasi:show-reservasi' %}" class="text-white hover:text-gray-300">Reservasi Pengguna</a></li>
                <li><a href="/hotels/" class="text-white hover:text-gray-300">Pemesanan Kamar</a></li>
                <li class="bg-red-600 px-2 py-2 flex items-center justify-center rounded-sm"><a href="/logout/" class="text-white hover:text-gray-300 ">Logout</a></li>
            </ul>
        </div>
        <div class="px-4 block md:hidden"> <!-- Tampil di layar kecil (md dan yang lebih kecil) -->
            <button id="mobile-menu-btn" class="text-white focus:outline-none">
                <svg class="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M4 6h16M4 12h16m-7 6h7"></path>
                </svg>
            </button>
        </div>
    </div>
    <!-- Bagian menu yang disembunyikan pada layar besar, ditampilkan pada layar kecil -->
    <div id="mobile-menu" class="hidden md:hidden ">
        <ul class="py-2">
            <li><a href="{% url 'reservasi:dashboard-pengguna' %}" class="block text-white py-2 px-4 hover:bg-blue-500">Dashboard Pengguna</a></li>
            <li><a href="{% url 'reservasi:show-reservasi' %}" class="block text-white py-2 px-4 hover:bg-blue-500">Reservasi Pengguna</a></li>
            <li><a href="/hotels/" class="block text-white py-2 px-4 hover:bg-blue-500">Pemesanan Kamar</a></li>
            <li><a href="/logout/" class="block text-white py-2 px-4 hover:bg-blue-500">Logout</a></li>
        </ul>
    </div>
</nav>
{% else %}
<nav class="bg-blue-700 py-4 fixed top-0 left-0 w-[100vw] z-20 px-4">
    <div class="container mx-auto flex items-center justify-between">
        <div class="px-4">
            <a href="#" class="text-white font-bold text-2xl">Sistel</a>
        </div>
        <div class="hidden md:block"> <!-- Hanya tampil di layar besar (md dan yang lebih besar) -->
            <ul class="flex space-x-4 items-center">
                <li><a href="{% url 'hotel:dashboard-hotel' %}" class="text-white hover:text-gray-300">Dashboard Hotel</a></li>
                <li><a href="/kamar-hotel/" class="text-white hover:text-gray-300">Kamar Hotel</a></li>
                <li><a href="/fasilitas/hotel_facilities/" class="text-white hover:text-gray-300">Fasilitas Hotel</a></li>
                <li><a href="/reservasi-hotel/hotel/" class="text-white hover:text-gray-300">List Reservasi Hotel</a></li>
                <li class="bg-red-600 px-2 py-2 flex items-center justify-center rounded-sm"><a href="/logout/" class="text-white hover:text-gray-300 ">Logout</a></li>
            </ul>
        </div>
        <div class="px-4 block md:hidden"> <!-- Tampil di layar kecil (md dan yang lebih kecil) -->
            <button id="mobile-menu-btn" class="text-white focus:outline-none">
                <svg class="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                        d="M4 6h16M4 12h16m-7 6h7"></path>
                </svg>
            </button>
        </div>
    </div>
    <!-- Bagian menu yang disembunyikan pada layar besar, ditampilkan pada layar kecil -->
    <div id="mobile-menu" class="hidden md:hidden ">
        <ul class="py-2">
            <li><a href="{% url 'hotel:dashboard-hotel' %}" class="text-white hover:text-gray-300">Dashboard Hotel</a></li>
            <li><a href="/kamar-hotel/" class="text-white hover:text-gray-300">Kamar Hotel</a></li>
            <li><a href="/fasilitas/hotel_facilities/" class="text-white hover:text-gray-300">Fasilitas Hotel</a></li>
            <li><a href="/reservasi-hotel/hotel/" class="text-white hover:text-gray-300">List Reservasi Hotel</a></li>
            <li><a href="/logout/" class="block text-white py-2 px-4 hover:bg-blue-500">Logout</a></li>
        </ul>
    </div>
</nav>
{% endif %}



<script>
    document.getElementById('mobile-menu-btn').addEventListener('click', function () {
        document.getElementById('mobile-menu').classList.toggle('hidden');
    });
</script>