hotel/urls.py
from django.urls import path
from .views import dashboard_hotel
app_name = 'hotel'

urlpatterns = [
    path('dashboard/', dashboard_hotel, name= 'dashboard-hotel'),
]

kamar_hotel/urls.py
from django.urls import path
from .views import *
app_name = 'kamar_hotel'

urlpatterns = [
    path('', kamar_hotel, name= 'kamar_hotel'),
    path('show_create_kamar_hotel/', show_create_kamar_hotel, name='show_create_kamar_hotel'),
    path('delete/', delete_kamar_fix, name='delete_kamar_hotel')
]

sistel/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hotel/', include('hotel.urls')),
    path('hotels/', include('hotels_and_reviews.urls')),
    path('reservasi/', include('reservasi.urls')),
    path('', include('authentication.urls')),
    path('reservasi-hotel/', include('reservasi_hotel.urls')),
    path('fasilitas/', include('fasilitas.urls')),

    path('kamar-hotel/', include('kamar_hotel.urls')),
]

kamar_hotel/models.py
from django.db import models

# Create your models here.

kamar_hotel/views.py
from kamar_hotel.query import *
from django.shortcuts import render, redirect, HttpResponseRedirect
from connect_postgres import execute_sql_query
from django.http import HttpRequest
from django.views.decorators.csrf import csrf_exempt
from sistel.helper.function import *
from django.db import connection, InternalError


# Create your views here.
def get_nama_branch_hotel(request):
	cursor = connection.cursor()
	cursor.execute("SET SEARCH_PATH TO SISTEL;")

	userData = request.session.get('user_data')
	email_user = userData['email']
 	
	query = sql_get_nama_branch_hotel(email_user)
	cursor.execute(query)
	data = parse(cursor)
	data_hotel = data[0]

	hotel_name = data_hotel['hotel_name']
	hotel_branch = data_hotel['hotel_branch']

	return hotel_name, hotel_branch

def kamar_hotel(request):
	nama_hotel, hotel_branch = get_nama_branch_hotel(request)

	context = {
		'is_hotel':True
	}
	cursor = connection.cursor()
	cursor.execute("SET SEARCH_PATH TO SISTEL;")

	query = sql_get_room(nama_hotel, hotel_branch)
	cursor.execute(query)
	data = parse(cursor)
	daftar_kamar = []
	for kamar in data:
		kamar['slug'] = title_to_slug(kamar['number'])
		daftar_kamar.append(kamar)
	context['data_kamar'] = daftar_kamar

	return render(request, "kamarhotel.html", context)

@csrf_exempt
def show_create_kamar_hotel(request):
	context = {
		'is_hotel':True
	}
	if request.method == 'POST':
		if 'submitKamar' in request.POST:
			nomor = request.POST.get('nomor')
			harga = request.POST.get('price')
			lantai = request.POST.get('lantai')
			data = create_kamar_hotel(request, nomor, harga, lantai)
			if data['success']:
				return redirect('kamar_hotel:kamar_hotel')
			else:
				context['message'] = parse_error_message(data['msg'])
	return render(request, "show_create_kamar_hotel.html", context)

@csrf_exempt
def create_kamar_hotel(request, nomor, harga, lantai):
	nama_hotel, hotel_branch = get_nama_branch_hotel(request)

	context = {}
	cursor = connection.cursor()
	cursor.execute("SET SEARCH_PATH TO SISTEL;")

	try:
		query = sql_insert_room(nomor, harga, lantai, nama_hotel, hotel_branch)
		cursor.execute(query)
	except InternalError as e:
		message = str(e)
		return {
			'success' : False,
			'msg' : message
		}
	else:
		return {
			'success' : True
		}
	
@csrf_exempt
def delete_kamar_fix(request):
	nomor = request.POST.get('nomor')
	email = request.session.get('user_data')['email']
	query = f"""SELECT hotel_name, hotel_branch from hotel where hotel.email = '{email}'; """
	res = execute_sql_query(query=query)[0]
	hotel_name = res[0]
	hotel_branch = res[1]
	execute_sql_query(f"""
		delete  from reservation_room where reservation_room.rhotelbranch = '{hotel_branch}' 
		AND reservation_room.rhotelname = '{hotel_name}' AND reservation_room.rnum = '{nomor}' ;
		delete  from room where room.hotel_branch = '{hotel_branch}' 
		AND room.hotel_name = '{hotel_name}' AND room.number = '{nomor}' 
		 RETURNING number;
""")
	return redirect('/kamar-hotel/')

def delete_kamar_hotel(request):
	nama_hotel, hotel_branch = get_nama_branch_hotel(request)
	nomor = request.POST.get('nomor')
	context = {}
	cursor = connection.cursor()
	cursor.execute("SET SEARCH_PATH TO SISTEL;")

	query = sql_delete_room(nomor, nama_hotel, hotel_branch)
	try:
		cursor.execute(query)
	except Exception as e:
		return {
			'success' : False,
			'msg' : 'Terdapat kesalahan'
		}
	else:
		return {
			'success' : True
		}

kamar_hotel/templates/kamarhotel.html
{% extends 'base-tw.html'%}
{% load static %}

{% block meta %}
<title>SISTEL | Daftar Kamar </title>
{% endblock meta %}

{% block content %}
{% include 'nav.html' with is_hotel=is_hotel %}

<main class="flex items-center justify-center min-h-screen">
  <div class="container mx-auto mt-5">
    <div class="p-6 bg-white shadow-md rounded-lg border border-primary">
      <h1 class="text-3xl mb-6 mt-12 text-primary text-center">Kamar Hotel</h1>
      <a href="{% url 'kamar_hotel:show_create_kamar_hotel' %}" class="inline-block mb-4">
        <button class="bg-blue-400 text-white px-4 py-2 rounded-md hover:bg-opacity-75 focus:outline-none">Tambah Kamar</button>
      </a>
      <table class="min-w-full bg-white border-collapse border border-gray-300">
        <thead class="bg-gray-800 text-white">
          <tr>
            <th class="py-2 px-4">Nomor Kamar</th>
            <th class="py-2 px-4">Harga</th>
            <th class="py-2 px-4">Lantai</th>
            <th class="py-2 px-4">Daftar Fasilitas</th>
            <th class="py-2 px-4">Hapus Kamar</th>
          </tr>
        </thead>
        <tbody>
          {% for kamar in data_kamar %}
          <tr class="border-t border-gray-300">
            <td class="py-2 px-4">{{ kamar.number }}</td>
            <td class="py-2 px-4">{{ kamar.price }}</td>
            <td class="py-2 px-4">{{ kamar.floor }}</td>
            <td class="py-2 px-4">{{ kamar.facilities }}</td>
            <td class="py-2 px-4">
              <form method="POST" action="/kamar-hotel/delete/">
                {% csrf_token %}
                <input type="text" name="nomor" class="hidden" value="{{kamar.number}}">
                <button class="bg-red-500 text-black px-3 py-1 rounded-md hover:bg-opacity-75 focus:outline-none"
                    type="submit">Pilih</button>
            </form>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</main>

<script>
  // Your JavaScript code here
</script>
{% endblock content %}

kamar_hotel/templates/show_create_kamar_hotel.html
{% extends 'base-tw.html'%}
{% load static %}

{% block meta %}
<title>SISTEL | Tambah Kamar </title>
{% endblock meta %}

{% block content %}
{% include 'nav.html' with is_hotel=is_hotel %}

<main class="flex justify-center items-center h-screen">
    <div class="w-full md:w-1/2 p-5 shadow-md border rounded-lg border-primary grad">
        <h1 class="text-center mb-4 text-primary text-3xl">Form Tambah Kamar</h1>
        <form id="form-submit-kamar" method="POST" action="{% url 'kamar_hotel:show_create_kamar_hotel' %}"
            class="space-y-4">
            {% csrf_token %}
            <div>
                <label for="inputNomor" class="block text-gray-700">Nomor Kamar</label>
                <input type="number" class="w-full border border-primary rounded-md py-2 px-3 focus:outline-none"
                    id="nomor" name="nomor" required>
            </div>
            <div>
                <label for="inputHarga" class="block text-gray-700">Harga</label>
                <input type="number" class="w-full border border-primary rounded-md py-2 px-3 focus:outline-none"
                    id="price" name="price" required>
            </div>
            <div>
                <label for="inputLantai" class="block text-gray-700">Lantai</label>
                <input type="number" class="w-full border border-primary rounded-md py-2 px-3 focus:outline-none"
                    id="lantai" name="lantai" required>
            </div>
            <div class="flex justify-center">
                <button class="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-opacity-75 focus:outline-none"
                    type="submit" name="submitKamar">Tambah Kamar</button>
            </div>
        </form>
    </div>
</main>

<script>
    // Your JavaScript code here
</script>
{% endblock content %}